---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec:
      containers:
        - name: cont1
          image: narasimhasai95/goalsapi:590236ae6c0948dc9905f336991dfa4aa2eb0c6f
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: "/app/logs"
              name: ebs-volume
          env:
            - name: MONGOURI
              valueFrom:
                secretKeyRef: 
                  name: backendsecrets
                  key: MONGOURI
            - name: MONGO_USER
              valueFrom:
                secretKeyRef: 
                  name: backendsecrets
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: backendsecrets
                  key: MONGO_PASSWORD 
            - name: PORT
              valueFrom:
                secretKeyRef: 
                  name: backendsecrets
                  key: PORT
      volumes:  
        - name: ebs-volume
          persistentVolumeClaim:
            claimName: ebs-pvc

