---
apiVersion: v1
kind: Namespace
metadata:
  name: goals-api-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: goals-api-ns
  labels:
    app: goals-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goals-api
  template:
    metadata:
      labels:
        app: goals-api
    spec:
      containers:
      - name: goals-api
        image: narasimhasai95/goalsapi:79aa811e80daad5581a6fe9ca65eafcc0a6445c8
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb+srv://sai:secret32412@cluster0.awxhn.mongodb.net/course-goals?retryWrites=true&w=majority"
        - name: PORT
          value: "3000"

