---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
  namespace: backend
spec:
  storageClassName: my-ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi