---
apiVersion: v1
kind: Service
metadata:
  name: goalsapiservice
  namespace: goals-api-ns
spec:
  type: LoadBalancer
  selector:
    app: goals-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: goalsapiservice2
  namespace: goals-api-ns
spec:
  type: ClusterIP
  selector:
    app: goals-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000